- hosts: localhost
  vars:
    # home: "{{ lookup('env', 'HOME') }}"
    user: "mokronos"
    home: "/home/{{ user }}"
  # pre_tasks:
  #   - name: Update Apt
  #     become: true
  #     apt:
  #       force_apt_get: true
  #       update_cache: true
  #     tags:
  #       - install
  #       - core
  tasks:
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dotfiles.yml
