- hosts: localhost
  # pre_tasks:
  #   - name: Update Apt
  #     become: true
  #     apt:
  #       force_apt_get: true
  #       update_cache: true
  #     tags:
  #       - install
  #       - core
  tasks:
    - import_tasks: tasks/zsh.yml
