#!/usr/bin/env/ bash

sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

ansible-pull -K -U https://github.com/mokronos/ansible.git
