- name: Remove Neovim
  shell: "rm -rf {{ home }}/neovim"
  become: true
  tags: &tags_nvim [ 'install', 'nvim' ]

- name: Install Neovim dependencies 
  apt:
    name: ["ninja-build", "gettext"]
  become: true
  tags: *tags_nvim

- name: Clone Neovim
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ home }}/neovim"
  tags: *tags_nvim

- name: Install Neovim
  shell: "cd {{ home }}/neovim && make CMAKE_BUILD_TYPE=Release && git checkout stable && make install"
  become: true
  tags: *tags_nvim

- name: Install neovim python
  ansible.builtin.pip:
    name: neovim
